### ISSUE TITLE
Usar versão 2.0.x do VCGE

### ISSUE THREAD

**Issue by ericof** [plonegovbr/brasil.gov.vcge#19]
Foi feito o release da versão 2.0.2 do VCGE (http://vocab.e.gov.br/id/governo#esquema).

Para utilização dela é necessário provermos um passo de migração com DE -> PARA sobre os termos utilizados (Houve redução considerável do número de termos).

**Comment by idgserpro** [comment]
Uma pergunta: o uso do VCGE 2.0 é uma determinação do Ministério, ou seja, toda vez que sai uma versão nova, deve-se atualizar todos os portais para a sua atualização, ou as versões 1.0 e 2.0 podem coexistir, ou seja, essa prerrogativa de escolha é do órgão que utilizar o VCGE? Consigo achar algum documento **oficial** contendo essa informação?

Se tem de atualizar por determinação do Ministério, então tem de simplesmente fazer o upgradeStep; Se não tem, ou mantém a branch 1.0.x, ou verifica se tem como implementar essa lógica de escolher a versão do VCGE.

P/C @ericof @hvelarde @caduvieira

**Comment by caduvieira** [comment]
Falar com o roberto.lyra at planejamento.gov.br

**Comment by idgserpro** [comment]
Segue o apoio do Roberto sobre essa questão:

> Embora a convivência seja possível, a recomendação é pela última versão. A documentação existente está ​disponível em https://www.governoeletronico.gov.br/eixos-de-atuacao/governo/interoperabilidade/vocabulario-controlado-do-governo-eletronico-vcge

> Não posso garantir se haja uma referência explicita a migrar para a versão mais nova, creio que isso ficou implícito, mas não explícito.

> Mas existe a prerrogativa de escolha, incluindo a opção de não usar o VCGE, em prol de um vocabulário local. 

Ele também afirmou que tentaria revisar a documentação para ter certeza se está explícita ou não essa recomendação mas não deu prazo, portanto, acho que o ideal é o recomendado acima.

**Comment by caduvieira** [comment]
Onde encontro uma documentação sobre disponibilizar o upgradestep para o admin? Assim o administrador escolhe se faz ou não como sugestão do @Augusto-herrmann

**Comment by hvelarde** [comment]
atualizado em https://github.com/plonegovbr/portal.buildout/commit/8e8d310ea2423d39e717f30b5c1f36f289aea35c
