### ISSUE TITLE
 VCGE 2.0.0 bug

### ISSUE THREAD

**Issue by AlexandreChagas** [plonegovbr/brasil.gov.vcge#25]
Prezados, se trata de um projeto novo. instalando o pacote do brasil.gov.portal, ele instala a versão do VCGE 2.0.0, detectei um problema ao editar o artigo que vem como exemplo de capa , a solução temporária que encontrei foi forçar a instalação do VCGE 1.0.2 (que funcionou perfeitamente)

Pacotes instalados: 

brasil.gov.barra = 1.0.2
brasil.gov.vcge = 1.0.2
brasil.gov.agenda = 1.0b3
brasil.gov.portal = 1.0.3
brasil.gov.temas = 1.0.5
collective.cover = 1.0a9
brasil.gov.tiles = 1.0.4

saudações e segue abaixo a tracebak:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module z3c.form.form, line 221, in **call**
  Module plone.directives.dexterity.form, line 77, in render
  Module z3c.form.form, line 158, in render
  Module Products.Five.browser.pagetemplatefile, line 59, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in **call**
  Module z3c.pt.pagetemplate, line 149, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 170, in render
  Module 54deea37f1af4c4079b48b22675fb959.py, line 164, in render
  Module d062ff707a724e12f6584dbfd4cc7873.py, line 1392, in render_master
  Module d062ff707a724e12f6584dbfd4cc7873.py, line 612, in render_content
  Module 54deea37f1af4c4079b48b22675fb959.py, line 150, in **fill_main
  Module 9cef0041569383f55bbaaef7f4db1257.py, line 1808, in render_titlelessform
  Module 9cef0041569383f55bbaaef7f4db1257.py, line 818, in render_fields
  Module 9cef0041569383f55bbaaef7f4db1257.py, line 126, in render_widget_rendering
  Module 9cef0041569383f55bbaaef7f4db1257.py, line 1077, in render_field
  Module five.pt.expressions, line 161, in __call**
  Module Products.Five.browser.metaconfigure, line 479, in **call**
  Module zope.browserpage.viewpagetemplatefile, line 83, in **call**
  Module zope.browserpage.viewpagetemplatefile, line 51, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in **call**
  Module z3c.pt.pagetemplate, line 149, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 170, in render
  Module 99f03a920af4f0d8bbee367b43bf8a81.py, line 590, in render
  Module 99f03a920af4f0d8bbee367b43bf8a81.py, line 465, in render_widget_wrapper
  Module five.pt.expressions, line 161, in **call**
  Module brasil.gov.vcge.dx.widget, line 90, in render
  Module zope.browserpage.viewpagetemplatefile, line 83, in **call**
  Module zope.browserpage.viewpagetemplatefile, line 51, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in **call**
  Module z3c.pt.pagetemplate, line 149, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 188, in render
  Module chameleon.template, line 170, in render
  Module f008867ee9523b356445939ee5607708.py, line 125, in render
  Module five.pt.expressions, line 154, in **call**
  Module five.pt.expressions, line 126, in traverse
  Module zope.traversing.adapters, line 136, in traversePathElement
- **traceback_info**: (<SkosWidget 'form.widgets.IVCGE.skos'>, 'existing')
  Module zope.traversing.adapters, line 42, in traverse
- **traceback_info**: (<SkosWidget 'form.widgets.IVCGE.skos'>, 'existing', ())
  Module brasil.gov.vcge.dx.widget, line 105, in existing
  Module zope.schema.vocabulary, line 133, in getTermByToken
  LookupError: http://vocab.e.gov.br/2011/03/vcge#informacoes-sobre-pais
  - Expression: "widget/@@ploneform-render-widget"
  - Filename:   ... rm-0.7.6-py2.7.egg/plone/app/z3cform/templates/macros.pt
  - Location:   (line 97: col 81)
  - Source:     ... place="structure widget/@@ploneform-render-widget"/>
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  - Expression: "view/existing"
  - Filename:   ... ov.vcge-2.0.0-py2.7.egg/brasil/gov/vcge/dx/skos_input.pt
  - Location:   (line 5: col 29)
  - Source:     ... al:values tal:repeat="item view/existing">
                                            ^^^^^^^^^^^^^
  - Arguments:  repeat: {...} (0)
             context: <ImplicitAcquisitionWrapper conheca-o-novo-modelo-da-identidade-digital-padrao-do-governo-federal at 0xa512780>
             views: <ViewMapper - at 0xcf53450>
             modules: <TraversableModuleImporter - at 0x3dcba90>
             args: <tuple - at 0x7ff861619dd0>
             nothing: <NoneType - at 0x76fdd0>
             target_language: <NoneType - at 0x76fdd0>
             default: <object - at 0x7ff87c274b60>
             request: <instance - at 0x7ff8600ed128>
             wrapped_repeat: {...} (0)
             loop: {...} (0)
             template: <ViewPageTemplateFile - at 0xc9fba10>
             translate: <function translate at 0x7ff8610f91b8>
             options: {...} (0)
             view: <SkosWidget IVCGE.skos at 0xcec8d90>

**Comment by idgserpro** [comment]
Esse erro permanece no último release no momento que escrevo esse comentário, 1.1.4. Basta acessar http://localhost:8080/Plone/noticias/conheca-o-novo-modelo-da-identidade-digital-padrao-do-governo-federal/edit para que o erro ocorra.

**Comment by caduvieira** [comment]
Creio que temos que alterar a instalação padrão para não conter itens do VCGE 1.0.2 se o VCGE instalado por padrão for o 2.0.X

**Comment by idgserpro** [comment]
Na verdade, o portal padrão não está compatível com o brasil.gov.vcge 2.0.x. Os conteúdos de exemplo foram criados com o vcge 1.x. Temos que recriar o conteúdo e fazer um upgrade step se formos utilizar o vcge 2.0.x.

Relacionaonado com: 
https://github.com/plonegovbr/brasil.gov.portal/issues/222
https://github.com/plonegovbr/brasil.gov.vcge/issues/19

**Comment by hvelarde** [comment]
isso aqui foi consertado no upgrade step mencionado acima.
