### ISSUE TITLE
Remover iw.debug do buildout

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.vcge#31]
Executei o buildout do projeto e ocorreu o erro:

https://github.com/plonegovbr/brasil.gov.vcge/issues/30

Esse erro é causado porque o ipython (dependência do iw.debug) não instala o pexpect ao executar o buildout. Eu não sabia se alguém estava usando o iw.debug, então não quis remover do buildout. O que eu fiz foi [adicionar o pexpect ao buildout](https://github.com/plonegovbr/brasil.gov.vcge/commit/f8e34f4997df6668b76b8cae024a612595ac8861). Parece que as pessoas são a favor de [remover o iw.debug do buildout](https://github.com/plonegovbr/brasil.gov.vcge/commit/c45345f4b91a1e2fc77b1a3e95aff3baf0f4055c). Eu não uso o iw.debug e também sou a favor de remover do buildout. Se alguém utiliza o  iw.debug, favor se manifestar.

**Comment by hvelarde** [comment]
@idgserpro mesmo se alguem usa o iw.debug essa pessoa pode colocar ele no seu ambiente; na minha opinião, pode remover.
