### ISSUE TITLE
Aumentar cobertura de teste com dexterity

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.vcge#33]
O coveralls está falhando porque a cobertura de teste do arquivo [/src/brasil/gov/vcge/dx/widget.py](https://github.com/plonegovbr/brasil.gov.vcge/blob/master/src/brasil/gov/vcge/dx/widget.py)  está baixa. Ver:

https://coveralls.io/builds/8138058

**Comment by idgserpro** [comment]
Se já tivéssemos testes robots dessa funcionalidade, a alteração feita em https://github.com/plonegovbr/brasil.gov.vcge/pull/36/files#diff-f94d665ed4ecff9a13f6871a833d6c5bR41 que foi descoberta de forma manual teria sido descoberta pelos testes automatizados.

**Comment by idgserpro** [comment]
Lembrar de, ao adicionar os testes de robots, de adicionar a linha

https://raw.githubusercontent.com/plone/plone.app.robotframework/master/versions.cfg

no extends do buildout.

**Comment by hvelarde** [comment]
a cobertura de testes atual é de 92%: https://coveralls.io/github/plonegovbr/brasil.gov.vcge
