### ISSUE TITLE
Corrigir code analysis no master

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.vcge#38]
https://travis-ci.org/plonegovbr/brasil.gov.vcge/jobs/278753702

https://travis-ci.org/plonegovbr/brasil.gov.vcge/jobs/278753822

**Comment by idgserpro** [comment]
Favor tratar isso em

https://github.com/plonegovbr/brasil.gov.vcge/tree/idgserpro-ci-webdriverfix-master

https://github.com/plonegovbr/brasil.gov.vcge/tree/idgserpro-ci-webdriverfix-master-1x

**Comment by hvelarde** [comment]
corrigido em: https://github.com/plonegovbr/brasil.gov.vcge/commit/ada012429f767eac6ab5b22b5ba36d4a7c48854d
